home/ubuntu/Trackstarz/memberships/urls.py
from django.urls import path, re_path

from .views import (
	MembershipSelectView, 
	PaymentView, 
	updateTransactions, 
	profile_view, 
	cancelSubscription
)

app_name = 'memberships'

urlpatterns = [
	path('', MembershipSelectView.as_view(), name='select'),
	path('payment/', PaymentView, name='payment'),
	path('update-transactions/<subscription_id>/', updateTransactions, name='update-transactions'),
	path('profile/', profile_view, name='profile'),
	path('cancel/', cancelSubscription, name='cancel'),
]

home/ubuntu/Trackstarz/memberships/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save

from datetime import datetime
import stripe
stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your models here.

MEMBERSHIP_CHOICES = (
	('Official Yearly', 'yrl'),
	('Official Monthly', 'mon'),
	('Universe', 'uni')
)

class Membership(models.Model):
	slug = models.SlugField()
	membership_type = models.CharField(
		choices=MEMBERSHIP_CHOICES,
		default='Universe',
		max_length=30)
	price = models.IntegerField(default=15)
	stripe_plan_id = models.CharField(max_length=40)

	def __str__(self):
		return self.membership_type

class UserMembership(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	stripe_customer_id = models.CharField(max_length=40)
	membership = models.ForeignKey(Membership, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.user.username

def post_save_usermembership_create(sender, instance, created, *args, **kwargs):
	if created:
		UserMembership.objects.get_or_create(user=instance)

	user_membership, created = UserMembership.objects.get_or_create(user=instance)

	if user_membership.stripe_customer_id is None or user_membership.stripe_customer_id == '':
		new_customer_id = stripe.Customer.create(email=instance.email)
		user_membership.stripe_customer_id = new_customer_id['id']
		user_membership.save()

post_save.connect(post_save_usermembership_create, sender=settings.AUTH_USER_MODEL)

class Subscription(models.Model):
	user_membership = models.ForeignKey(UserMembership, on_delete=models.CASCADE)
	stripe_subscription_id = models.CharField(max_length=40)
	active = models.BooleanField(default=True)

	def __str__(self):
		return self.user_membership.user.username

	@property
	def get_created_date(self):
		subscription = stripe.Subscription.retrieve(self.stripe_subscription_id)
		return datetime.fromtimestamp(subscription.created)

	@property
	def get_next_billing_date(self):
		subscription = stripe.Subscription.retrieve(self.stripe_subscription_id)
		return datetime.fromtimestamp(subscription.current_period_end)

home/ubuntu/Trackstarz/memberships/views.py
from django.conf import settings

from django.contrib import messages

from django.http import HttpResponseRedirect

from django.shortcuts import render, redirect, get_object_or_404

from django.views.generic import ListView

from .models import Membership, UserMembership, Subscription

from django.urls import reverse

import stripe

from userprofile.models import userprofile

from django.contrib.auth import get_user_model

from memberships.serializers import MembershipSerializer, UserMembershipSerializer, SubscriptionSerializer

from rest_framework import viewsets



# Create your views here.
User = get_user_model()

class MembershipView(viewsets.ModelViewSet):
    serializer_class = MembershipSerializer
    queryset = Membership.objects.all()


class UserMembershipView(viewsets.ModelViewSet):
    serializer_class = UserMembershipSerializer
    queryset = UserMembership.objects.all()


class SubscriptionView(viewsets.ModelViewSet):
    serializer_class = SubscriptionSerializer
    queryset = Subscription.objects.all()



def profile_view(request):
	
	user_membership = get_user_membership(request)
	user_subscription = get_user_subscription(request)
	context = {
		'user_membership': user_membership,
		'user_subscription': user_subscription
	}
	return render(request, "memberships/profile.html", context)






def get_user_membership(request):
	user_membership_qs = UserMembership.objects.filter(user=request.user)
	if user_membership_qs.exists():
		return user_membership_qs.first()
	return None

def get_user_subscription(request):
	user_subscription_qs = Subscription.objects.filter(
		user_membership=get_user_membership(request))
	if user_subscription_qs.exists():
		user_subscription = user_subscription_qs.first()
		return user_subscription
	return None

def get_selected_membership(request):
	membership_type = request.session['selected_membership_type']
	selected_membership_qs = Membership.objects.filter(
		membership_type=membership_type)
	if selected_membership_qs.exists():
		return selected_membership_qs.first()
	return None


class MembershipSelectView(ListView):
	model = Membership

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(**kwargs)
		current_membership = get_user_membership(self.request)
		context['current_membership'] = str(current_membership.membership)
		return context

	def post(self, request, **kwargs):
		selected_membership_type = request.POST.get('membership_type')
		
		user_membership = get_user_membership(request)
		user_subscription = get_user_subscription(request)

		selected_membership_qs = Membership.objects.filter(
			membership_type=selected_membership_type)

		if selected_membership_qs.exists():
			selected_membership = selected_membership_qs.first()


		if user_membership.membership == selected_membership:
			if user_subscription != None:
				messages.info(request, "You already have this membership. Your \
				next payment is due {}".format('get this value from stripe'))
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

		#assign to the session
		request.session['selected_membership_type'] = selected_membership.membership_type

		return HttpResponseRedirect(reverse('memberships:payment'))

def PaymentView(request):

	user_membership = get_user_membership(request)

	selected_membership = get_selected_membership(request)

	publishKey = settings.STRIPE_PUBLISHABLE_KEY
	
	if request.method == "POST":
		try:
			token = request.POST['stripeToken']
			
			customer = stripe.Customer.modify(
				user_membership.stripe_customer_id,
				source = token
			)


			subscription = stripe.Subscription.create(
				customer=user_membership.stripe_customer_id,
				items=[
					{
						"plan": selected_membership.stripe_plan_id,
					},
				],
				
			)
			
			return redirect(reverse('memberships:update-transactions', 
				kwargs={
					'subscription_id': subscription.id
				}))		
			
		except stripe.error.CardError as e:
			messages.info(request, "Your card has been declined")
			
	context = {
		'publishKey': publishKey,
		'selected_membership': selected_membership
	}

	return render(request, "memberships/membership_payment.html", context)
	
def updateTransactions(request, subscription_id):
		
		user_membership = get_user_membership(request)
		selected_membership = get_selected_membership(request)
		
		user_membership.membership = selected_membership
		user_membership.save()
		
		sub, created = Subscription.objects.get_or_create(user_membership=user_membership)
		sub.stripe_subscription_id = subscription_id
		sub.active = True
		sub.save()
		
		try:
			del request.session['selected_membership_type']
		except:
			pass
			
		messages.info(request, "Successfully created {} membership".format(selected_membership))
		return redirect('/memberships')		
		
		
		
def cancelSubscription(request):
	user_sub = get_user_subscription(request)

	if user_sub.active == False:
		messages.info(request, "You dont have an active membership")
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

	sub = stripe.Subscription.retrieve(user_sub.stripe_subscription_id)
	sub.delete()

	user_sub.active = False
	user_sub.save()

	free_membership = Membership.objects.filter(membership_type='Free').first()
	user_membership = get_user_membership(request)
	user_membership.membership = free_membership
	user_membership.save()

	messages.info(request, "successfully cancelled membership. We have sent an email")

	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



		
		
		
		
		
		
		
		
		
		

home/ubuntu/Trackstarz/memberships/templates/memberships/membership_list.html
{% extends 'userprofile/base.html' %}

{% block content %}
<div class="container">
	<h1>Select a membership</h1>
	<div class="row">
		{% for object in object_list %}
			<div class="col-sm-4 col-md-4">
			<h2>{{ object.membership_type }}</h2>
			{% if forloop.first %}
				<p>Price: FREE</p>
			{% elif forloop.last %}
				<p>Price: ${{ object.price }}<small>/year</small></p>
			{% else %}
				<p>Price: ${{ object.price }}<small>/month</small></p>
			{% endif %}

			{% if forloop.first %}
				<form method="POST"  action="/">
						{% csrf_token %}
						{% if object.membership_type != current_membership %}
							<button class="btn btn-warning">Select</button>
						{% else %}
							<small>This is your current membership</small>
						{% endif %}
						<input type="hidden" name="membership_type" value="{{ object.membership_type }}">
				</form>
			{% else %}
				<form method="POST" action="{% url 'memberships:select' %}">
					{% csrf_token %}
					{% if object.membership_type != current_membership %}
						<button class="btn btn-warning">Select</button>
					{% else %}
						<small>This is your current membership</small>
					{% endif %}
					<input type="hidden" name="membership_type" value="{{ object.membership_type }}">
				</form>
			{% endif %}
			</div>
		{% endfor %}
	</div>
</div>

{% endblock content %}

home/ubuntu/Trackstarz/memberships/templates/memberships/membership_payment.html
{% extends 'userprofile/base.html' %}
{% load static %}

{% block content %}




<div class="container">
	<div class="row">
		<h1>Payment</h2>
		<div class="col-sm-12 col-md-12">
      <p>Selected membership: {{ selected_membership }}</p>
      <p>Price: <strong>${{ selected_membership.price }}</strong><small>/month</p>
      
      <script src="https://js.stripe.com/v3/"></script>

      <form action="." method="post" id="payment-form">
        {% csrf_token %}
          
            <label for="card-element">
              Credit or debit card
            </label> 
            <div class="form-row">
            <div id="card-element" style="width:30em; margin-top:28px;">
              
            </div>
          
            <!-- Used to display form errors. -->
            <div id="card-errors" role="alert"></div> 
          
          <button class="stripe">Submit Payment</button>
        </div>
      </form>
  
    </div>
  </div>


 <div id="stripe-token-handler" class="is-hidden">Success! Got token: <span class="token"></span></div>

		
</div>
	

<!-- script for the stripe form -->

<script src="{% static 'js/checkout.js' %}"></script>





{% endblock content %}

home/ubuntu/Trackstarz/memberships/templates/memberships/profile.html
{% extends 'userprofile/base.html' %}

{% block content %}
<div class="container">
	<div class="row">
	<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
	{% include "blog/includes/homesidebarleft.html" %}
	</div>
	<div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
		<h1>My Profile</h1>
			{% if user_subscription != None %}
				<h4>Current Membership: {{ user_membership.membership.membership_type }} <small>since {{ user_subscription.get_created_date }}</small></h4>
				
				{% if user_subscription.active != False %}
					<p>Next payment due: {{ user_subscription.get_next_billing_date }}
					</p>

					<div class="box">
						<a class="button" href="#popup1">Cancel Subscription</a>
					</div>
						   
						<div id="popup1" class="overlay">
							<div class="popup">
								<h3>Are You Sure?</h3>
								<a class="close" href="#">×</a>
								<div class="content">
									<a href="{% url 'memberships:cancel' %}">Yes</a>
								</div>
							</div>
						</div>






					

				{% else %}
					<p>You don't have an active membership plan.  Check them out here:	
						<a href="{% url 'memberships:select' %}"></a>
					</p>
				{% endif %}			

			{% else %}
				<p>You dont have a subscription!</p>
			{% endif %}
		

		

		
	</div>		
		
	</div>
</div>
{% endblock content %}